# Generated by Django 5.1.6 on 2025-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorie_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FermetureMultiJours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(max_length=200)),
                ('notifier_clients', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fermeture multi-jours',
                'verbose_name_plural': 'Fermetures multi-jours',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FermetureSpecifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('type_fermeture', models.CharField(choices=[('journee', 'Journée complète'), ('matin', 'Fermé le matin'), ('soir', 'Fermé le soir')], default='journee', max_length=10)),
                ('motif', models.CharField(max_length=200)),
                ('notifier_clients', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fermeture spécifique',
                'verbose_name_plural': 'Fermetures spécifiques',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FrequenceCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalle', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (45, '45 minutes'), (60, '60 minutes')], default=30, verbose_name='Intervalle entre les créneaux')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification')),
            ],
        ),
        migrations.CreateModel(
            name='HoraireHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('ferme', 'Fermé'), ('ferme_matin', 'Fermé le matin'), ('ferme_soir', 'Fermé le soir')], default='ouvert', max_length=20)),
                ('ouverture_matin', models.TimeField(default='07:00')),
                ('fermeture_matin', models.TimeField(default='15:00')),
                ('ouverture_soir', models.TimeField(default='15:00')),
                ('fermeture_soir', models.TimeField(default='20:00')),
            ],
            options={
                'verbose_name': 'Horaire hebdomadaire',
                'verbose_name_plural': 'Horaires hebdomadaires',
                'ordering': ['jour'],
            },
        ),
    ]
