# Generated by Django 5.1.6 on 2025-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_frequencecollecte_options_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='code_recuperation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
